cloudcasa release v2.0.0
rancher/partner-charts pull request #106
Opened 2021-06-29 10:22 UTC by nitishdsharma

**Updates**
----------------
1. Adding Cloudcasa v2.0.0 release.
2. Added support for Backup on Azure.
3. Added support for snapshot copy.

2021-06-29 10:25 UTC, nitishdsharma commented
@PennyScissors 
Please let me know the reason behind the Validation failure. Here we intend to push a new release version v2.0.0.

2021-06-30 19:41 UTC, PennyScissors commented
Hello @nitishdsharma, please run `make charts` and add everything that gets updated into a separate commit with the message "Make charts". This is now a necessary step that needs to be done in a separate commit once you are done adding/updating your chart so that validation passes.

2021-07-19 22:20 UTC, PennyScissors commented
Hey @nitishdsharma, can you take me through the steps you took to test this within Rancher? I tried deploying it, but it doesn't seem to work. Do I need to do something to acquire a `Cluster ID` or configure the chart in a specific way in order to install it? Thanks

2021-07-19 22:44 UTC, PennyScissors requested changes
Hey @nitishdsharma, can you take me through the steps you took to test this within Rancher? I tried deploying it, but it doesn't seem to work. Do I need to do something to acquire a `Cluster ID` or configure the chart in a specific way in order to install it? Thanks

2021-07-20 14:17 UTC, nitishdsharma commented
> Hey @nitishdsharma, can you take me through the steps you took to test this within Rancher? I tried deploying it, but it doesn't seem to work. Do I need to do something to acquire a `Cluster ID` or configure the chart in a specific way in order to install it? Thanks

Hi @PennyScissors, 
Could you please go through the shared link. https://cloudcasa.io/getstarted/. Just follow steps 1 and 2 and fetch the clusterID. Provide that ClusterID in CloudCasa Partner Chart UI and try installing it.

2021-07-26 13:39 UTC, nitishdsharma commented
@PennyScissors Can you please follow the steps to get the clusterid and provide it while installing the CloudCasa partner chart.

2021-07-26 18:17 UTC, PennyScissors requested changes
@nitishdsharma please test this chart within Rancher. I followed the steps, but it still won't install correctly.

2021-07-26 18:17 UTC, PennyScissors commented on packages/cloudcasa/generated-changes/patch/Chart.yaml.patch
> -+annotations:
This needs to be added back.

2021-07-26 18:17 UTC, PennyScissors commented on packages/cloudcasa/generated-changes/patch/Chart.yaml.patch
> ++#icon: https://raw.githubusercontent.com/catalogicsoftware/cloudcasa-helmchart/gh-pages/logo.png
Can you remove those comments to avoid cluttering the patch file? It should be okay to just replace it with the new URL.

2021-07-27 06:35 UTC, nitishdsharma commented
@PennyScissors I have made the required changes, can you please review it. Also I have tested it by consuming the cloudcasav2.0.0  on a Rancher manager server and registered a test cluster with CloudCasa. The state of the cluster is active and its taking the required backups and snapshots. Please let me know in case of any query.
Thanks.

2021-07-27 23:25 UTC, PennyScissors approved these changes
Looks good! Thank you for taking the time to figure those out.

2021-07-27 23:26 UTC, merged