Update Haproxy chart to 1.16.1
rancher/partner-charts pull request #125
Opened 2021-07-28 08:38 UTC by andrewheberle

This PR updates the HAproxy Helm chart version to 1.16.1 which includes version 1.6.5 of the HAProxy Kubernetes Ingress Controller.

2021-07-30 13:20 UTC, andrewheberle commented on packages/haproxy/generated-changes/patch/Chart.yaml.patch
>  +  catalog.cattle.io/release-name: haproxy
The display-name annotation has been added and the upstream chart already includes a kubeVersion value

2021-08-03 21:57 UTC, PennyScissors commented
Could you please drop the following commits, then run a new `make charts` and commit in a new last commit?
1. Add HAProxy 1.16.1 built assets `614d614` (first `make charts` you ran)
2. Update generated chart `0d72727` (second `make charts` you ran)

The current behavior in our scripts has a bug that won't reconstruct the index based on the latest annotations so your display name annotation update is not being added to the index and therefore missing from the UI.

2021-08-03 21:58 UTC, PennyScissors requested changes
@andrewheberle could you please drop the following commits, then run a new `make charts` and commit assets/ charts/ and index.yaml in a new last commit?
1. Add HAProxy 1.16.1 chart build c635e8f (first `make charts` you ran)
2. Add HAProxy 1.16.1 built assets 614d614 (first `make charts` you ran)
3. Update generated chart 0d72727 (second `make charts` you ran)

The current behavior in our scripts has a bug that won't reconstruct the index based on the latest annotations so your display name annotation update is not being added to the index and therefore missing from the UI.

2021-08-16 08:07 UTC, andrewheberle commented
@PennyScissors those commits have been dropped so there is now just the two in my branch, so hopefully that's all good to go.

2021-08-20 20:45 UTC, PennyScissors commented
Hello @andrewheberle, could you please drop the last make charts commit, re-run make charts, and create a new commit once again? We recently merged a fix for our scripts that affected existing PRs and chart will need to be regenerated. Thanks! The PR looks good, so it should be ready to approve after.

2021-08-23 00:20 UTC, andrewheberle commented
Commit `8e21fc6` has been dropped and new `make charts` added as commit `06b2a87`, however this failed CI checks.

Should I rebase my branch back onto `main-source` and start from scratch?

2021-08-23 22:12 UTC, PennyScissors commented
@andrewheberle Before you try rebasing and doing it from scratch, try dropping the commit again, then run `make pull-scripts` and then `make charts`. It should generate a chart in assets named `haproxy-1.16.100.tgz` rather than `haproxy-1.16.100+up1.16.1.tgz` since we disabled appending the build metadata.

2021-08-24 05:31 UTC, andrewheberle commented
I initially re-did the process with the `make pull-scripts` however that still pulled down v0.2.1 of the build scripts so I went ahead and rebased my branch off "main-source" and started from scratch so I ended up with the v0.2.2 build scripts.

Hopefully 5th time lucky :)

2021-08-24 20:42 UTC, PennyScissors approved these changes
Looks good now! Thank you, I appreciate your patience.

FYI, we switched to doing batch releases so this will not be released on merge. I currently have a PR open to release a few other partner charts so I will add yours to it to hopefully get this released sooner. Here is the [PR](https://github.com/rancher/partner-charts/pull/143) if you want to keep track of it.

2021-08-24 20:45 UTC, merged