adds aws-event-sources chart by TriggerMesh
rancher/partner-charts pull request #133
Opened 2021-08-11 11:27 UTC by sameersbn

2021-08-11 20:08 UTC, PennyScissors requested changes
Looks good overall, tested deployment in Rancher and it works fine. Just one small change and it should be good to approve and merge. Please make sure you drop the `make charts` commit (34e903a), and create a new one after your changes to pass our validation. The `make charts` commit should always be the last in your PR.

2021-08-11 20:08 UTC, PennyScissors commented on packages/aws-event-sources/package.yaml
> +packageVersion: 00
Can you change this to `01`?

2021-08-16 04:50 UTC, sameersbn commented on packages/aws-event-sources/package.yaml
> +packageVersion: 00
updated

2021-08-20 20:50 UTC, PennyScissors commented
Hello @sameersbn , could you please drop the last make charts commit, re-run make charts, and create a new commit once again? We recently merged a fix for our scripts that affected existing PRs and charts will need to be regenerated. Thanks!

2021-08-23 05:55 UTC, sameersbn commented
> could you please drop the last make charts commit, re-run make charts, and create a new commit once again?

@PennyScissors done!

2021-08-24 00:11 UTC, PennyScissors approved these changes

2021-08-24 00:12 UTC, merged