Added WekaIO CSI plugin
rancher/partner-charts pull request #69
Opened 2021-01-21 16:01 UTC by sergeyberezansky

2021-01-21 22:01 UTC, PennyScissors requested changes
Please update this PR to include your package only, which should contain your package.yaml, patch file, and overlay directory with contents, all in a single commit. Our drone will take care of building and publishing the assets once it's merged. Make sure you save your changes the patch file and then clean the working directory as stated [here](https://github.com/rancher/partner-charts/tree/main-source#8-pull-request) before submitting a PR.

2021-01-22 06:10 UTC, sergeyberezansky commented
> Please update this PR to include your package only, which should contain your package.yaml, patch file, and overlay directory with contents, all in a single commit. Our drone will take care of building and publishing the assets once it's merged. Make sure you save your changes the patch file and then clean the working directory as stated [here](https://github.com/rancher/partner-charts/tree/main-source#8-pull-request) before submitting a PR.

Hello, 
Unfortunately, make clean doesn't clear all the relevant files that were generated during validation.
I have submitted now only the required directory together with the patch file, hopefully everything is OK.
But it would be really nice if you could take care of `make clean` to retain only the necessary files, or at least better explain in the documentation which files exactly should be pushed in PR
Thank you

2021-01-26 05:02 UTC, PennyScissors commented
@sergeyberezansky Thanks for the feedback, I'll update the documentation accordingly.

I tried deploying the generated chart locally using Helm 3, and within Rancher but ran into problems. When using Helm 3 locally, it falls into a crash loop, and in Rancher it just times out and fails. My advice would be to figure out why it doesn't work using Helm 3 locally first, and then run Rancher from out docker image and setup a custom catalog with your chart to troubleshoot it.

There are also a few minor changes that will need to be done, so I'll try and explain a little better what is the expected workflow and hopefully make it easier for you. Assuming the repo is at a clean state (fresh clone), the general flow at a high level is as following:

1. run `make prepare CHART=csi-wekafs` to pull upstream into the charts directory (packages/csi-wekafs/charts, not the one in the root directory)
2. do whatever changes you need in packages/csi-wekafs/charts (You would address comments in this step)
3. run `make prepare CHART=csi-wekafs` to save those changes in the patch file
4. run `make clean` to clean everything up (This doesn't delete everything that was generated, but it does delete packages/csi-wekafs/charts, which shouldn't be included in the PR).
5. run `make validate CHART=csi-wekafs` to validate and generate the new assets (The new chart with the overlay files added on, patch applied, and package version added onto the chart's file name, `assets/csi-wekafsplugin-0.6.300.tgz`).
6. And finally if validation looks good and installing `assets/csi-wekafsplugin-0.6.300.tgz` using Helm locally works fine, you are good to submit a PR which should only contain the files I mentioned in my previous comment (Basically `git add /packages/csi-wekafs` after cleaning up).
7. spin up Rancher from docker hub, create a cluster, and create a custom catalog with your chart to test it within Rancher.

2021-01-26 05:15 UTC, PennyScissors reviewed
@sergeyberezansky Thanks for the feedback, I'll update the documentation accordingly.

I tried deploying the generated chart locally using Helm 3, and within Rancher but ran into problems. When using Helm 3 locally, it falls into a crash loop, and in Rancher it just times out and fails. My advice would be to figure out why it doesn't work using Helm 3 locally first, and then run Rancher from out docker image and setup a custom catalog with your chart to troubleshoot it.

There are also a few minor changes that will need to be done, so I'll try and explain a little better what is the expected workflow and hopefully make it easier for you. Assuming the repo is at a clean state (fresh clone), the general flow at a high level is as following:

1. run `make prepare CHART=csi-wekafs` to pull upstream into the charts directory (packages/csi-wekafs/charts, not the one in the root directory)
2. do whatever changes you need in packages/csi-wekafs/charts (You would address comments in this step)
3. run `make prepare CHART=csi-wekafs` to save those changes in the patch file
4. run `make clean` to clean everything up (This doesn't delete everything that was generated, but it does delete packages/csi-wekafs/charts, which shouldn't be included in the PR).
5. run `make validate CHART=csi-wekafs` to validate and generate the new assets (The new chart with the overlay files added on, patch applied, and package version added onto the chart's file name, `assets/csi-wekafs/csi-wekafsplugin-0.6.300.tgz`).
6. And finally if validation looks good and installing `assets/csi-wekafs/csi-wekafsplugin-0.6.300.tgz` using Helm locally works fine, you are good to submit a PR which should only contain the files I mentioned in my previous comment (Basically `git add /packages/csi-wekafs` after cleaning up all in a single commit).
7. spin up Rancher from docker hub, create a cluster, and create a custom catalog with your chart to test it within Rancher.

2021-01-26 05:15 UTC, PennyScissors commented on packages/csi-wekafs/csi-wekafs.patch
> ++++ packages/csi-wekafs/charts/app-readme.md
The contents of `app-readme.md` and `questions.yaml` shouldn't be in the patch. They are and should be in the overlay directory which is basically where you keep files that you want added in the resulting tgz in assets/csi-wekafs once it gets generated. Please delete them from `packages/csi-wekafs/charts` after the make prepare step. They will then get automatically removed from the patch once you do the make patch step after.

2021-01-26 05:15 UTC, PennyScissors commented on packages/csi-wekafs/csi-wekafs.patch
> ++  - https://github.com/weka/csi-wekafs/tree/v0.6.3/deploy/helm/csi-wekafsplugin
Optional, as it does no harm. Remove this extra space if you want to avoid clutter in the patch.

2021-01-26 05:15 UTC, PennyScissors commented on packages/csi-wekafs/csi-wekafs.patch
> ++questions:
Same thing as the comment above in the `app-readme.md` stuff.

2021-01-26 05:15 UTC, PennyScissors commented on packages/csi-wekafs/csi-wekafs.patch
> ++version: 0.6.300
Change the chart version back from `0.6.300` to `0.6.3`. This is done as part of the validation or charts generation step for the resulting asset. Sometimes, if you forget to do a make clean you could end up saving this in the patch by mistake.

2021-01-27 17:16 UTC, PennyScissors approved these changes
lgtm

2021-01-27 17:16 UTC, merged